// STORED ACTIVITIES
export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';
export const REORDER_ACTIVITIES = 'REORDER_ACTIVITIES';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';

// ROUTINE DATA
export const LOAD_ROUTINE = 'LOAD_ROUTINE';
export const UPDATE_ROUTINE = 'UPDATE_ROUTINE';
export const REORDER_QUEUE = 'REORDER_QUEUE';
export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';

// SESSION
export const LOAD_SESSION = 'LOAD_SESSION';
export const LOAD_SESSION_QUEUE = 'LOAD_SESSION_QUEUE'
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const SET_TIME_POSITION = 'SET_TIME_POSITION';
export const START_SESSION = 'START_SESSION';
export const PAUSE_SESSION = 'PAUSE_SESSION';
export const RESET_SESSION = 'RESET_SESSION';
export const END_SESSION = 'END_SESSION';

// HISTORY
export const LOAD_HISTORY = 'LOAD_HISTORY';
export const ADD_HISTORY = 'ADD_HISTORY';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';